baseURL = 'https://lizorn.com/'
locale = 'zh-CN'
title = '山海炼物'
theme = 'minimal'

[params]
  description = '山海炼物 — 炼物成器，格物致知'
  subtitle = 'Refining Ideas, Crafting Reality'
  author = 'Lizorn'
  twitter = 'https://x.com/AbyssEdgeX'
  wechat = ''

[menu]
  [[menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/about/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 20
